apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
spec:
  type: LoadBalancer
  selector:
    app: fraud-detection
  ports:
    - protocol: TCP
      port: 5006 # External port
      targetPort: 5006 # Container port
